### ISSUE TITLE
Our Whole Website offline due to my mistake

### ISSUE THREAD

**Issue by PCTipsGR** [NeotiDev/neotidev.github.io#1]
I just changed the title thinking it would be better for neotidev.github.io to redirect to js.org version.

:man_facepalming: 

I realized that Netlify probably was picking Neotipage as the name of the branch. I just took our whole website offline :clap: 

Could you @yagizhan49 please update the name to Netlify so that the correct branch is showing up?

**Comment by mahofficial** [comment]
Hi, the website doesn't seems to be offline. https://neotidev.cf is working on my side

**Comment by PCTipsGR** [comment]
https://neotidev.js.org/ doesn't though, The reason why I did not assign you is because none of us has access to the Netlify settings of this repo except the owner.

**Comment by mahofficial** [comment]
Yes, neotidev.js.org is not working!

**Comment by yagizhan49** [comment]
Just checked the issue, now Netlify deploys from the updated repository. However, js.org needs to merge the PR in order to get it working.
